version: '3.9'

services:
  nest-app:
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
